server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /utilisateur/ {
        proxy_pass http://backend:9090/utilisateur/;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /produit/ {
        proxy_pass http://backend:9090/produit/;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /entrepot/ {
        proxy_pass http://backend:9090/entrepot/;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /stock/ {
        proxy_pass http://backend:9090/stock/;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /mouvement/ {
        proxy_pass http://backend:9090/mouvement/;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /dashboard/ {
        proxy_pass http://backend:9090/dashboard/;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }
}